rules:
  no-console: 0
  no-param-reassign: 0
  semi: [2, "never"]
  radix: ["error", "as-needed"]
  jsx-quotes: ["error", "prefer-single"]
  no-else-return: "off"

parserOptions:
  ecmaVersion: 6
  sourceType: module
