author: <%= username %>
title: <%= username %>.github.io
domain: <%= username %>.github.io
theme: <%= theme %>
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'site_builder_node.js']

# Site Builder
screenshot_directory: ./assets/images/screenshots/
screenshot_width: 1280
screenshot_height: 800
repositories:
<%= repositories.map(repo =>   `  - repo_url: ${repo.html_url}`).join('\n\n'); %>
