author: <%= username %>
title: <%= username %>.github.io
domain: <%= username %>.github.io
theme: <%= theme %>
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'repository_scraper.js']
screenshot_directory: ./assets/images/screenshots/

# Repository Scraper
screenshot_width: 1280
screenshot_height: 800
repositories:
<%= repositories.map(repo =>   `  - repo_url: ${repo.html_url}`).join('\n\n'); %>
